version: "3"

services:
  web:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$MYSQLDB_DOCKER_PORT
   
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - 3307:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080